### ISSUE TITLE
Ongoing updates from a file: I can update existing data for a new reporting period. 

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#89]
# [Designs](https://share.goabstract.com/450467f7-8cff-47c9-a10d-4d9eac8bf51a)

https://user-images.githubusercontent.com/63253539/103302485-c9595700-49d1-11eb-9f5c-ef8c5a8c383f.mp4

- [ ] #101 – Upload spreadsheet with updated data
- [ ] #103 – Detect and display record change types
- [ ] #102  – Preview changes to records
- [ ] #236 – Uploaded data is reconciled with existing data for site/org
- [ ] #239  - Preview updates before adding the changes to your roster
- [ ] #992  Step Indicator UI Component (already exists in USWDS)
- [ ] #1000 Turn error modal into its own page

- Confirmation alert on the roster after upload (already exists in current experience)

Potential future improvements not included in this implementation:
#257 - Download a spreadsheet that flags missing/incorrect data.
#238 – Resolve flow to match or add new records

**Comment by RyanHansz** [comment]
- get example starter data, possibly from ECE reporter participants
- Use scenarios in this spreadsheet https://docs.google.com/spreadsheets/d/1peyU1RT__if9Hv1YIHFEvEF82LQZm2pUW922J-B3T0w/edit#gid=753156949
to test changes

**Comment by RyanHansz** [comment]
Letting people operate on a preview of data before committing to uploading

**Comment by JordanGuinn** [comment]
Created https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1079 as the Zenhub equivalent of this (which is an actual epic, allowing for issue management and tracking progress).  Closing this in favor of that.
